name: mattspy
channels:
  - conda-forge
dependencies:
  - cloudpickle
  - importlib_metadata
  - joblib
  - loky
  - numpy
  - scipy
  - setuptools_scm
  - setuptools_scm_git_archive
  - pytest
  - pytest-xdist
  - pip
  - setuptools
