name: tests

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.10
          channels: conda-forge
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet \
            --file=requirements.txt
          python -m pip install -e .
          conda install -y -q \
            flake8 \
            pytest \
            pytest-xdist \
            black

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 mattspy
          black --check --diff mattspy

      - name: test
        shell: bash -l {0}
        run: |
          pytest -n 2 -vv mattspy
