name: tests

on:
  push:
    branches:
      - main
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v5

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: mattspy
          create-args: python=3.10

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          pip install --no-deps --no-build-isolation -e .

      - name: test
        shell: bash -l {0}
        run: |
          export JAX_ENABLE_X64=1
          pytest -n 2 -vv mattspy
